image: gitlab/dind

variables:
  DOCKER_DRIVER: overlay
  DEMO_CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DEV_CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  STAGING_CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

services:
  - docker:dind

stages:
  - build_staging
  - deploy_staging
  - build_demo
  # - deploy_demo

before_script:
  - docker version
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - chmod +x ./setup_env_staging.sh
  - ./setup_env_staging.sh

build_staging:
  stage: build_staging
  script:
    - docker build -t $STAGING_CONTAINER_IMAGE
      --build-arg REACT_APP_HOST="$REACT_APP_HOST_STAGING"
      --build-arg	REACT_APP_WMSX_URL="$REACT_APP_WMSX_STAGING_URL"
      --build-arg	REACT_APP_MMSX_URL="$REACT_APP_MMSX_STAGING_URL"
      --build-arg	REACT_APP_NOTIFICATION_HOST="$REACT_APP_NOTIFICATION_STAGING_HOST"
      --build-arg	REACT_APP_SOCKET_NOTIFICATION_HOST="$REACT_APP_SOCKET_NOTIFICATION_STAGING_HOST"
      --build-arg	REACT_APP_VTI_DOMAIN="$REACT_APP_VTI_STAGING_DOMAIN" --no-cache .
    - docker commit $STAGING_CONTAINER_IMAGE
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
deploy_staging:
  stage: deploy_staging
  variables:
    GIT_STRATEGY: none
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
  script:
    - eval `ssh-agent -s`

    - bash -c 'echo "$SSH_PRIVATE_KEY" | ssh-add -'
    - mkdir -p ~/.ssh

    - ssh-keyscan -H $SSH_SERVER_IP >> ~/.ssh/known_hosts

    - mkdir -p ~/.ssh

    - chmod 644 ~/.ssh/known_hosts

    - >
      ssh $SSH_STAGING_USER@$SSH_SERVER_IP
      "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY};
      docker pull ${STAGING_CONTAINER_IMAGE};
      docker stop  mesx_grand_stg_web || true; 
      docker run --rm -d --name mesx_grand_stg_web -p 10088:80 ${STAGING_CONTAINER_IMAGE};
      docker image prune -f;"

build_demo:
  before_script:
    - docker version
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ls -la
    - chmod +x ./setup_env_demo.sh
    - ./setup_env_demo.sh
  stage: build_demo
  script:
    - echo "$REACT_APP_DEMO_HOST"
    - docker build --tag $DEMO_CONTAINER_IMAGE
      --build-arg REACT_APP_HOST="$REACT_APP_DEMO_HOST"
      --build-arg	REACT_APP_WMSX_URL="$REACT_APP_WMSX_DEMO_URL"
      --build-arg	REACT_APP_MMSX_URL="$REACT_APP_MMSX_DEMO_URL"
      --build-arg	REACT_APP_QMSX_URL="$REACT_APP_QMSX_DEMO_URL"
      --build-arg	REACT_APP_NOTIFICATION_HOST="$REACT_APP_NOTIFICATION_DEMO_HOST"
      --build-arg	REACT_APP_SOCKET_NOTIFICATION_HOST="$REACT_APP_SOCKET_NOTIFICATION_DEMO_HOST"
      --build-arg	REACT_APP_VTI_DOMAIN="$REACT_APP_VTI_DOMAIN"  .
    - docker push $DEMO_CONTAINER_IMAGE
  only:
    - master
# deploy_demo:
#   stage: deploy_demo
#   variables:
#     GIT_STRATEGY: none
#   only:
#     - master
#   script:
#     - eval `ssh-agent -s`

#     - bash -c 'echo "$SSH_PRIVATE_KEY" | ssh-add -'
#     - mkdir -p ~/.ssh

#     - ssh-keyscan -H $SSH_SERVER_IP >> ~/.ssh/known_hosts

#     - mkdir -p ~/.ssh

#     - chmod 644 ~/.ssh/known_hosts

#     - >
#       ssh $SSH_USER@$SSH_SERVER_IP
#       "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY};
#       cd ${PATH_TO_DEMO_PROJECT};
#       docker pull ${DEMO_CONTAINER_IMAGE};
#       docker-compose down;
#       docker-compose up -d;
#       docker image prune -f;"
