version: '3.8'

services:
  aveneu-demo-web:
    image: registry.vti.com.vn/snp_smartwms/source/web:avenue_dev
    ports:
      - '12000:80'
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - avenue-demo-wms-network
networks:
  avenue-demo-wms-network:
    external: true
