version: '3.7'

services:
  stg-mesx-web:
    image: registry.vti.com.vn/snp_smartwms/source/web:stg
    ports:
      - '10088:80'
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
