version: '3.7'

services:
  p-mesx-web:
    image: registry.vti.com.vn/snp_smartwms/source/web:master
    ports:
      - '10088:80'
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
